ALTER TABLE devices FORCE ROW LEVEL SECURITY;
ALTER TABLE runs FORCE ROW LEVEL SECURITY;
ALTER TABLE evaluations FORCE ROW LEVEL SECURITY;
ALTER TABLE skill_dispositions FORCE ROW LEVEL SECURITY;
ALTER TABLE policy_bundles FORCE ROW LEVEL SECURITY;
ALTER TABLE judge_provider_configs FORCE ROW LEVEL SECURITY;
ALTER TABLE ingest_events FORCE ROW LEVEL SECURITY;
ALTER TABLE ingest_outbox FORCE ROW LEVEL SECURITY;
