export const CODEX_RUNTIME_VERSION_PROBE_TIMEOUT_MILLISECONDS = 1_000;
export const CODEX_WORKER_CHALLENGE_TIMEOUT_MILLISECONDS = 1_000;
export const CODEX_SUPERVISION_FETCH_TIMEOUT_MILLISECONDS = 10_000;
export const CODEX_PLUGIN_COMMAND_TIMEOUT_MILLISECONDS = 15_000;
